-- Assets table with self-referencing hierarchy
CREATE TABLE IF NOT EXISTS asset (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  id_parent INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (id_parent) REFERENCES asset(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Variable Attributes table (now linked directly to assets)
CREATE TABLE IF NOT EXISTS variable_attribute (
  id INT AUTO_INCREMENT PRIMARY KEY,
  asset_id INT NOT NULL,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(255),
  format_data VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Attribute Values table (stores the actual values)
CREATE TABLE IF NOT EXISTS attribute_value (
  id INT AUTO_INCREMENT PRIMARY KEY,
  asset_id INT NOT NULL,
  attribute_id INT NOT NULL,
  value VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE CASCADE,
  FOREIGN KEY (attribute_id) REFERENCES variable_attribute(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- History table (tracks attribute value changes)
CREATE TABLE IF NOT EXISTS history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  asset_id INT NOT NULL,
  attribute_id INT NOT NULL,
  value VARCHAR(100) NOT NULL,
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE CASCADE,
  FOREIGN KEY (attribute_id) REFERENCES variable_attribute(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Production Orders table
CREATE TABLE IF NOT EXISTS production_order (
  id INT AUTO_INCREMENT PRIMARY KEY,
  material_number VARCHAR(20),
  serial_number VARCHAR(5),
  ts_from TIMESTAMP NULL,
  ts_to TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Processes table
CREATE TABLE IF NOT EXISTS process (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  ts_from TIMESTAMP NULL,
  result CHAR(1),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES production_order(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Process Steps table
CREATE TABLE IF NOT EXISTS process_step (
  id INT AUTO_INCREMENT PRIMARY KEY,
  process_id INT NOT NULL,
  ts_from TIMESTAMP NULL,
  ts_to TIMESTAMP NULL,
  result CHAR(1),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (process_id) REFERENCES process(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Steps table
CREATE TABLE IF NOT EXISTS step (
  id INT AUTO_INCREMENT PRIMARY KEY,
  process_step_id INT NOT NULL,
  result CHAR(1),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (process_step_id) REFERENCES process_step(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Step Assets (junction table)
CREATE TABLE IF NOT EXISTS step_asset (
  id INT AUTO_INCREMENT PRIMARY KEY,
  step_id INT NOT NULL,
  asset_id INT NOT NULL,
  result CHAR(1),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (step_id) REFERENCES step(id) ON DELETE CASCADE,
  FOREIGN KEY (asset_id) REFERENCES asset(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Result Details table
CREATE TABLE IF NOT EXISTS result_detail (
  id INT AUTO_INCREMENT PRIMARY KEY,
  step_id INT NOT NULL,
  update_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (step_id) REFERENCES step(id) ON DELETE CASCADE,
  FOREIGN KEY (update_id) REFERENCES history(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci; 